/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UsainSprintPages.UserAdmin;

import Controller.UserAdmin.CreateUserRoleController;
import Controller.UserAdmin.DeleteUserRoleController;
import Controller.UserAdmin.ModifyUserRoleController;
import Controller.UserAdmin.ViewUserRoleController;
import model.Role;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Eechang
 */
public class UserAdminManageUserRolePage extends javax.swing.JFrame {

    /**
     * Creates new form UserAdminManageUserRolePage
     */
    private static final int JF_W = 1353;
    private static final int JF_H = 710;

    public void getFrame() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocation(JF_W, JF_H);
    }

    public UserAdminManageUserRolePage() {
        initComponents();
        lblUserRoleExist.setVisible(false);

    }

    public UserAdminManageUserRolePage(String ShowNa) {
        initComponents();
        ShowName.setText(ShowNa);
        BtnCreate.setEnabled(false);
        BtnModify.setEnabled(false);
        BtnClear.setEnabled(false);
        BtnDelete.setEnabled(false);
        URbtn.setEnabled(false);
        lblUserRoleExist.setVisible(false);
    }

    public void validateFields() {
        String roleName = txtUserRoleName.getText();
        if (!roleName.equals("")) {
            BtnCreate.setEnabled(true);
        } else {
            BtnCreate.setEnabled(false);
        }
        if (!roleName.equals("")) {
            BtnModify.setEnabled(true);
        } else {
            BtnModify.setEnabled(false);
        }
        if (!roleName.equals("")) {
            BtnClear.setEnabled(true);
        } else {
            BtnClear.setEnabled(false);
        }
        if (!roleName.equals("")) {
            BtnDelete.setEnabled(true);
        } else {
            BtnDelete.setEnabled(false);
        }
    }

    public void clear() {
        txtUserRoleName.setText("");
        lblUserRoleID.setText("");
        BtnCreate.setEnabled(false);
        BtnModify.setEnabled(false);
        BtnClear.setEnabled(false);
        BtnDelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserAccBtn = new javax.swing.JPanel();
        UaLable = new javax.swing.JLabel();
        ShowName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        URbtn = new javax.swing.JPanel();
        Urlasble = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchUserRoleName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblUserRoleID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUserRoleName = new javax.swing.JTextField();
        lblUserRoleExist = new javax.swing.JLabel();
        BtnCreate = new javax.swing.JButton();
        BtnModify = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1353, 710));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 31, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserAccBtn.setBackground(new java.awt.Color(0, 31, 125));
        UserAccBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserAccBtnMousePressed(evt);
            }
        });

        UaLable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        UaLable.setForeground(new java.awt.Color(255, 255, 255));
        UaLable.setText("User Account");
        UaLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UaLableMousePressed(evt);
            }
        });

        javax.swing.GroupLayout UserAccBtnLayout = new javax.swing.GroupLayout(UserAccBtn);
        UserAccBtn.setLayout(UserAccBtnLayout);
        UserAccBtnLayout.setHorizontalGroup(
            UserAccBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserAccBtnLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(UaLable, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        UserAccBtnLayout.setVerticalGroup(
            UserAccBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserAccBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UaLable, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(UserAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 190, -1));

        ShowName.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 18)); // NOI18N
        ShowName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ShowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, 40));

        jLabel12.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hello");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 10));

        URbtn.setBackground(new java.awt.Color(0, 63, 125));
        URbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                URbtnMousePressed(evt);
            }
        });

        Urlasble.setBackground(new java.awt.Color(2, 62, 138));
        Urlasble.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Urlasble.setForeground(new java.awt.Color(255, 255, 255));
        Urlasble.setText("User Roles");
        Urlasble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UrlasbleMousePressed(evt);
            }
        });

        javax.swing.GroupLayout URbtnLayout = new javax.swing.GroupLayout(URbtn);
        URbtn.setLayout(URbtnLayout);
        URbtnLayout.setHorizontalGroup(
            URbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(URbtnLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(Urlasble, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        URbtnLayout.setVerticalGroup(
            URbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, URbtnLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(Urlasble, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(URbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 190, 60));

        logoutBtn.setBackground(new java.awt.Color(0, 31, 125));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutBtnMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Logout");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jLabel18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel18KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout logoutBtnLayout = new javax.swing.GroupLayout(logoutBtn);
        logoutBtn.setLayout(logoutBtnLayout);
        logoutBtnLayout.setHorizontalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        logoutBtnLayout.setVerticalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 190, 50));

        jLabel19.setFont(new java.awt.Font("Academy Engraved LET", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Usain Sprint");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 710));

        jPanel2.setBackground(new java.awt.Color(20, 33, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search by user role name:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 46, -1, -1));

        txtSearchUserRoleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchUserRoleNameKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearchUserRoleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 44, 277, 32));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1170, 120));

        jPanel3.setBackground(new java.awt.Color(20, 33, 61));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Role ID", "Role Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 40, 500, -1));

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*Click on row to select");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 17, -1, -1));

        lblUserRoleID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserRoleID.setForeground(new java.awt.Color(255, 255, 255));
        lblUserRoleID.setText("00");
        jPanel3.add(lblUserRoleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 52, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Role ID:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 52, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Role Name:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 106, -1, -1));

        txtUserRoleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserRoleNameKeyReleased(evt);
            }
        });
        jPanel3.add(txtUserRoleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 102, 256, 31));

        lblUserRoleExist.setForeground(new java.awt.Color(255, 0, 0));
        lblUserRoleExist.setText("User role already exists");
        jPanel3.add(lblUserRoleExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 139, -1, 20));

        BtnCreate.setBackground(new java.awt.Color(139, 195, 74));
        BtnCreate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnCreate.setText("Create");
        BtnCreate.setPreferredSize(new java.awt.Dimension(111, 36));
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });
        jPanel3.add(BtnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, 40));

        BtnModify.setBackground(new java.awt.Color(139, 195, 74));
        BtnModify.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnModify.setText("Modify");
        BtnModify.setPreferredSize(new java.awt.Dimension(111, 36));
        BtnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifyActionPerformed(evt);
            }
        });
        jPanel3.add(BtnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 120, 40));

        BtnClear.setBackground(new java.awt.Color(139, 195, 74));
        BtnClear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        jPanel3.add(BtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 120, 40));

        BtnDelete.setBackground(new java.awt.Color(139, 195, 74));
        BtnDelete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnDelete.setText("Delete");
        BtnDelete.setPreferredSize(new java.awt.Dimension(111, 36));
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(BtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 1160, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserRoleNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserRoleNameKeyReleased
        lblUserRoleExist.setVisible(false);
        validateFields();
        CreateUserRoleController Cuc = new CreateUserRoleController();
        Cuc.Checknames = txtUserRoleName.getText();
        if (Cuc.CheckName()) {
            BtnCreate.setEnabled(false);
            BtnModify.setEnabled(false);
            BtnDelete.setEnabled(false);
            lblUserRoleExist.setVisible(true);
        }
    }//GEN-LAST:event_txtUserRoleNameKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        Iterator<Role> itr = ViewUserRoleController.getdata();
        while (itr.hasNext()) {
            Role roleObj = itr.next();
            dtm.addRow(new Object[]{roleObj.getRoleId(), roleObj.getRoleName()});
        }


    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String RoleId = model.getValueAt(index, 0).toString();
        lblUserRoleID.setText(RoleId);
        String roleName = model.getValueAt(index, 1).toString();
        txtUserRoleName.setText(roleName);
        BtnModify.setEnabled(true);
        BtnDelete.setEnabled(true);
        BtnClear.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtSearchUserRoleNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUserRoleNameKeyReleased
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + txtSearchUserRoleName.getText().trim(), 1));
    }//GEN-LAST:event_txtSearchUserRoleNameKeyReleased

    private void URbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_URbtnMousePressed
        // TODO add your handling code here:
        String e = ShowName.getText();
        setVisible(false);
        new UserAdminManageUserRolePage(e).setVisible(true);
    }//GEN-LAST:event_URbtnMousePressed

    private void logoutBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMousePressed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new LoginPage().setVisible(true);
        }

    }//GEN-LAST:event_logoutBtnMousePressed

    private void UserAccBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserAccBtnMousePressed
        // TODO add your handling code here:
        String ShowNa = this.ShowName.getText();
        setVisible(false);
        new UserAdminManageUserAccountPage(ShowNa).setVisible(true);
    }//GEN-LAST:event_UserAccBtnMousePressed

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        // TODO add your handling code here:
        CreateUserRoleController Cur = new CreateUserRoleController();
        Cur.Name = txtUserRoleName.getText();
        Cur.createUserRoleController();
        setVisible(false);
        new UserAdminManageUserRolePage().setVisible(true);
    }//GEN-LAST:event_BtnCreateActionPerformed

    private void BtnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifyActionPerformed
        // TODO add your handling code here:
        ModifyUserRoleController MUR = new ModifyUserRoleController();
        MUR.Rid = Integer.parseInt(lblUserRoleID.getText());
        MUR.Rname = txtUserRoleName.getText();
        MUR.modifyUserRoleController();
        setVisible(false);
        new UserAdminManageUserRolePage().setVisible(true);
    }//GEN-LAST:event_BtnModifyActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete role?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            DeleteUserRoleController DUR = new DeleteUserRoleController();
            DUR.Rname = txtUserRoleName.getText();
            DUR.deleteUserRoleController();
            setVisible(false);
            new UserAdminManageUserRolePage().setVisible(true);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void UrlasbleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UrlasbleMousePressed
        // TODO add your handling code here:
        String e = ShowName.getText();
        setVisible(false);
        new UserAdminManageUserRolePage(e).setVisible(true);
    }//GEN-LAST:event_UrlasbleMousePressed

    private void UaLableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UaLableMousePressed
        // TODO add your handling code here:
        String ShowNa = this.ShowName.getText();
        setVisible(false);
        new UserAdminManageUserAccountPage(ShowNa).setVisible(true);
    }//GEN-LAST:event_UaLableMousePressed

    private void jLabel18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel18KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18KeyPressed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAdminManageUserRolePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAdminManageUserRolePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAdminManageUserRolePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAdminManageUserRolePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new UserAdminManageUserRolePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnCreate;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnModify;
    private javax.swing.JLabel ShowName;
    private javax.swing.JPanel URbtn;
    private javax.swing.JLabel UaLable;
    private javax.swing.JLabel Urlasble;
    private javax.swing.JPanel UserAccBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblUserRoleExist;
    private javax.swing.JLabel lblUserRoleID;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JTextField txtSearchUserRoleName;
    private javax.swing.JTextField txtUserRoleName;
    // End of variables declaration//GEN-END:variables
}
