/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UsainSprintPages.UserAdmin;

import java.util.Iterator;
import model.Account;
import java.awt.Dimension;
import javax.swing.RowFilter;
import Controller.UserAdmin.CreateUserAccountController;
import Controller.UserAdmin.DeleteUserAccountController;
import Controller.UserAdmin.ModifyUserAccountController;
import Controller.UserAdmin.ViewUserAccountController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Role;

/**
 *
 * @author Eechang
 */
public class UserAdminManageUserAccountPage extends javax.swing.JFrame {
    
    private static final int JF_W = 1353;
    private static final int JF_H = 710;

     public void getFrame()
     {
         setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         setLocation(JF_W,JF_H);
     }
  
    private int Sta;
    /**
     * Creates new form UserAdminManageUserAccountPage
     */
    public String emailPattern = "^[a-zA-z0-9]+[@]+[a-zA-z0-9]+[.]+[a-zA-z0-9]+$";
    public String phoneNumberPattern = "^[8-9]+[0-9]*$";

    public UserAdminManageUserAccountPage() {
        initComponents();
        lblUsernameExist.setVisible(false);
    }
    
    public UserAdminManageUserAccountPage(String Sname) {
        initComponents();
        ShowNa.setText(Sname);
        BtnCreate.setEnabled(false);
        BtnModify.setEnabled(false);
        BtnClear.setEnabled(false);
        BtnDelete.setEnabled(false);
        URbtn.setEnabled(false);
        txtUsername.setEditable(true);
        lblUsernameExist.setVisible(false);
    }

    public void clear() {
        txtUsername.setText("");
        txtPassword.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        Status.clearSelection();
        txtUsername.setEditable(true);
        BtnModify.setEnabled(false);
        
        BtnDelete.setEnabled(false);
    }

    public void validateFields() {
        String AccUsername = txtUsername.getText();
        String AccPassword = txtPassword.getText();
        String AccName = txtName.getText();
        String AccPhone = txtPhone.getText();
        String AccEmail = txtEmail.getText();
        int phoneLength = AccPhone.length();
        if (!AccUsername.equals("") && (!AccPassword.equals("")) && (!AccName.equals("")) && (!AccPhone.equals("")) && (!AccEmail.equals("") && (AccPhone.matches(phoneNumberPattern)) && (AccEmail.matches(emailPattern)) && (phoneLength == 8))) {
            BtnCreate.setEnabled(true);
        } else {
            BtnCreate.setEnabled(false);
        }
        if (!AccUsername.equals("") && (!AccPassword.equals("")) && (!AccName.equals("")) && (!AccPhone.equals("")) && (!AccEmail.equals("") && (AccPhone.matches(phoneNumberPattern)) && (AccEmail.matches(emailPattern)) && (phoneLength == 8))) {
            BtnModify.setEnabled(true);
        } else {
            BtnModify.setEnabled(false);
        }
        if (!AccUsername.equals("") && (!AccPassword.equals("")) && (!AccName.equals("")) && (!AccPhone.equals("")) && (!AccEmail.equals("") && (AccPhone.matches(phoneNumberPattern)) && (AccEmail.matches(emailPattern)) && (phoneLength == 8))) {
            BtnClear.setEnabled(true);
        } else {
            BtnClear.setEnabled(false);
        }
        if (!AccUsername.equals("") && (!AccPassword.equals("")) && (!AccName.equals("")) && (!AccPhone.equals("")) && (!AccEmail.equals("") && (AccPhone.matches(phoneNumberPattern)) && (AccEmail.matches(emailPattern)) && (phoneLength == 8))) {
            BtnDelete.setEnabled(true);
        } else {
            BtnDelete.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Status = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UserAccBtn = new javax.swing.JPanel();
        Uacc = new javax.swing.JLabel();
        ShowNa = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        URbtn = new javax.swing.JPanel();
        UserRolesB = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        LogoutLable = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchUsername = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtRole = new javax.swing.JComboBox<>();
        lblAccId = new javax.swing.JLabel();
        Open = new javax.swing.JRadioButton();
        Close = new javax.swing.JRadioButton();
        lblUsernameExist = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BtnCreate = new javax.swing.JButton();
        BtnModify = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1353, 710));
        setSize(new java.awt.Dimension(1500, 750));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Role");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 390, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password", "Name", "Phone", "Email", "Role", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 1140, 250));

        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("*Click on row to select");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Account ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 390, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 31, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserAccBtn.setBackground(new java.awt.Color(0, 63, 125));
        UserAccBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserAccBtnMousePressed(evt);
            }
        });

        Uacc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Uacc.setForeground(new java.awt.Color(255, 255, 255));
        Uacc.setText("User Account");
        Uacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UaccMousePressed(evt);
            }
        });

        javax.swing.GroupLayout UserAccBtnLayout = new javax.swing.GroupLayout(UserAccBtn);
        UserAccBtn.setLayout(UserAccBtnLayout);
        UserAccBtnLayout.setHorizontalGroup(
            UserAccBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserAccBtnLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(Uacc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        UserAccBtnLayout.setVerticalGroup(
            UserAccBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserAccBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Uacc, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(UserAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 190, -1));

        ShowNa.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 18)); // NOI18N
        ShowNa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ShowNa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 40));

        jLabel12.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hello");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 10));

        URbtn.setBackground(new java.awt.Color(0, 31, 125));
        URbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                URbtnMousePressed(evt);
            }
        });

        UserRolesB.setBackground(new java.awt.Color(2, 62, 138));
        UserRolesB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        UserRolesB.setForeground(new java.awt.Color(255, 255, 255));
        UserRolesB.setText("User Roles");
        UserRolesB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserRolesBMousePressed(evt);
            }
        });

        javax.swing.GroupLayout URbtnLayout = new javax.swing.GroupLayout(URbtn);
        URbtn.setLayout(URbtnLayout);
        URbtnLayout.setHorizontalGroup(
            URbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(URbtnLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(UserRolesB, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        URbtnLayout.setVerticalGroup(
            URbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, URbtnLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(UserRolesB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(URbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 190, 60));

        logoutBtn.setBackground(new java.awt.Color(0, 31, 125));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutBtnMousePressed(evt);
            }
        });

        LogoutLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LogoutLable.setForeground(new java.awt.Color(255, 255, 255));
        LogoutLable.setText("Logout");
        LogoutLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutLableMousePressed(evt);
            }
        });

        javax.swing.GroupLayout logoutBtnLayout = new javax.swing.GroupLayout(logoutBtn);
        logoutBtn.setLayout(logoutBtnLayout);
        logoutBtnLayout.setHorizontalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(LogoutLable, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        logoutBtnLayout.setVerticalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addComponent(LogoutLable, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 190, 50));

        jLabel19.setFont(new java.awt.Font("Academy Engraved LET", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Usain Sprint");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 190, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 710));

        jPanel3.setBackground(new java.awt.Color(20, 33, 61));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search:");

        txtSearchUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtSearchUsername.setToolTipText("");
        txtSearchUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchUsernameActionPerformed(evt);
            }
        });
        txtSearchUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchUsernameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1160, -1));

        jPanel4.setBackground(new java.awt.Color(20, 33, 61));

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        lblAccId.setForeground(new java.awt.Color(255, 255, 255));
        lblAccId.setText("00");

        Status.add(Open);
        Open.setForeground(new java.awt.Color(255, 255, 255));
        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        Status.add(Close);
        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        lblUsernameExist.setForeground(new java.awt.Color(255, 0, 0));
        lblUsernameExist.setText("Username already exists");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAccId)
                        .addGap(66, 66, 66)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Open)
                        .addGap(5, 5, 5)
                        .addComponent(Close))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblUsernameExist)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccId)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Open)
                    .addComponent(Close))
                .addGap(7, 7, 7)
                .addComponent(lblUsernameExist, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 1160, 160));

        jPanel5.setBackground(new java.awt.Color(20, 33, 61));

        BtnCreate.setBackground(new java.awt.Color(252, 163, 17));
        BtnCreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnCreate.setText("Create");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        BtnModify.setBackground(new java.awt.Color(252, 163, 17));
        BtnModify.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnModify.setText("Modify");
        BtnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifyActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(252, 163, 17));
        BtnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnClear.setBackground(new java.awt.Color(252, 163, 17));
        BtnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.setPreferredSize(new java.awt.Dimension(89, 28));
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(BtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(BtnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 1160, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtSearchUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchUsernameActionPerformed

    }//GEN-LAST:event_txtSearchUsernameActionPerformed

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        lblUsernameExist.setVisible(false);
        validateFields();
    CreateUserAccountController Cnc  = new CreateUserAccountController();
        Cnc.Checknames = txtUsername.getText();
        if (Cnc.CheckName()) {
            BtnCreate.setEnabled(false);
            BtnModify.setEnabled(false);
            BtnDelete.setEnabled(false);
            lblUsernameExist.setVisible(true);
        }
        BtnClear.setEnabled(true);
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        validateFields();
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        validateFields();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
        validateFields();
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        validateFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
          DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
          Iterator<Account> allacc=ViewUserAccountController.getAlldata();
          Iterator<Role> allacc2=ViewUserAccountController.getAllRoles();
          while(allacc2.hasNext()){
              Role roles = allacc2.next();
              txtRole.addItem(roles.getRoleName());
          }
          while (allacc.hasNext()) {
              
                    Account accountObj = allacc.next();
                    dtm.addRow(new Object[]{accountObj.getAccId(), accountObj.getAccUsername(), accountObj.getAccPassword(), accountObj.getAccName(), accountObj.getAccPhone(), accountObj.getAccEmail(), accountObj.getAccRole(), accountObj.getStatus()});
                }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String AccId = model.getValueAt(index, 0).toString();
        lblAccId.setText(AccId);
        String AccUsername = model.getValueAt(index, 1).toString();
        txtUsername.setText(AccUsername);
        txtUsername.setEditable(false);
        String AccPassword = model.getValueAt(index, 2).toString();
        txtPassword.setText(AccPassword);
        String AccName = model.getValueAt(index, 3).toString();
        txtName.setText(AccName);
        String AccPhone = model.getValueAt(index, 4).toString();
        txtPhone.setText(AccPhone);
        String AccEmail = model.getValueAt(index, 5).toString();
        txtEmail.setText(AccEmail);
        String AccRole = model.getValueAt(index, 6).toString();
        txtRole.setSelectedItem(AccRole);
        String status = model.getValueAt(index, 7).toString();

        if (status.equals("Open")) {
            Open.setSelected(true);
        } else {
            Close.setSelected(true);
        }
        BtnModify.setEnabled(true);
        BtnDelete.setEnabled(true);
        BtnClear.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtSearchUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUsernameKeyReleased
                  DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)"+ txtSearchUsername.getText().trim(),1));
    }//GEN-LAST:event_txtSearchUsernameKeyReleased

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        Sta = 1;
    }//GEN-LAST:event_OpenActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        Sta = 0;
    }//GEN-LAST:event_CloseActionPerformed

    private void URbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_URbtnMousePressed
        // TODO add your handling code here:
        String S = ShowNa.getText();
        setVisible(false);
        new UserAdminManageUserRolePage(S).setVisible(true);
    }//GEN-LAST:event_URbtnMousePressed

    private void logoutBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMousePressed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnMousePressed

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        // TODO add your handling code here:
        String Username = txtUsername.getText();
        String Password= txtPassword.getText();
        String Name = txtName.getText();
        String Phone = txtPhone.getText();
        String Email = txtEmail.getText();
        CreateUserAccountController CUA = new CreateUserAccountController();
        CUA.Username=Username;
        CUA.Name=Name;
        CUA.Password=Password;
        CUA.Email=Email;
        CUA.Phone=Phone;
        CUA.Roles=(String)txtRole.getSelectedItem();
        if (Sta == 1) {
            CUA.Status="Open";
        } else {
            CUA.Status="Close";
        }
        CUA.createAccountController();
        setVisible(false);
        new UserAdminManageUserAccountPage().setVisible(true);
    }//GEN-LAST:event_BtnCreateActionPerformed

    private void BtnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifyActionPerformed
        // TODO add your handling code here:
        ModifyUserAccountController MUA= new ModifyUserAccountController();
        MUA.Id = Integer.parseInt(lblAccId.getText());
        MUA.Username=txtUsername.getText();
        MUA.Password= txtPassword.getText();
        MUA.Name=txtName.getText();
        MUA.Phone=txtPhone.getText();
        MUA.Email=txtEmail.getText();
        MUA.Roles=(String) txtRole.getSelectedItem();
        if (Sta == 1) {
            MUA.Status="Open";
        } else {
            MUA.Status="Close";
        }
       MUA.modifyAccountController();
        setVisible(false);
        new UserAdminManageUserAccountPage().setVisible(true);
    }//GEN-LAST:event_BtnModifyActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
         clear();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete account?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
        DeleteUserAccountController DRc = new DeleteUserAccountController();
        DRc.Name = txtUsername.getText();
        DRc.deleteAccountController();
        setVisible(false);
        new UserAdminManageUserAccountPage().setVisible(true);
        }
        
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void LogoutLableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLableMousePressed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_LogoutLableMousePressed

    private void UserAccBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserAccBtnMousePressed
        // TODO add your handling code here:
         String S = ShowNa.getText();
           setVisible(false);
        new UserAdminManageUserRolePage(S).setVisible(true);
    }//GEN-LAST:event_UserAccBtnMousePressed

    private void UserRolesBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserRolesBMousePressed
        // TODO add your handling code here:
        String S = ShowNa.getText();
        setVisible(false);
        new UserAdminManageUserRolePage(S).setVisible(true);
    }//GEN-LAST:event_UserRolesBMousePressed

    private void UaccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UaccMousePressed
        // TODO add your handling code here:
        String S = ShowNa.getText();
           setVisible(false);
        new UserAdminManageUserRolePage(S).setVisible(true);
    }//GEN-LAST:event_UaccMousePressed

    private void LogoutLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLableMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new LoginPage().setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutLableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAdminManageUserAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAdminManageUserAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAdminManageUserAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAdminManageUserAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAdminManageUserAccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnCreate;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnModify;
    private javax.swing.JRadioButton Close;
    private javax.swing.JLabel LogoutLable;
    private javax.swing.JRadioButton Open;
    private javax.swing.JLabel ShowNa;
    private javax.swing.ButtonGroup Status;
    private javax.swing.JPanel URbtn;
    private javax.swing.JLabel Uacc;
    private javax.swing.JPanel UserAccBtn;
    private javax.swing.JLabel UserRolesB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAccId;
    private javax.swing.JLabel lblUsernameExist;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JComboBox<String> txtRole;
    private javax.swing.JTextField txtSearchUsername;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
